name: Prod - Build and Deploy

on:
  push:
    branches: [ main ]

env:
  PROJECT_ID: ${{ secrets.PROJECT_ID }}
  SERVICE_NAME: ${{ secrets.SERVICE_NAME }}
  RUN_REGION: ${{ secrets.RUN_REGION }}

jobs:
  setup-build-deploy:
    name: Setup, Build and Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v1'
      with:
        credentials_json: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
    - name: Configure docker
      run: |
        gcloud auth configure-docker $RUN_REGION-docker.pkg.dev
    - name: Build
      run: |
        docker build -t "$RUN_REGION-docker.pkg.dev/$PROJECT_ID/web/$SERVICE_NAME:latest" .
    - name: Detele previous images
      run: gcloud container images delete "$RUN_REGION-docker.pkg.dev/$PROJECT_ID/web/$SERVICE_NAME:latest" --force-delete-tags
      continue-on-error: true
    - name: Publish
      run: |
        docker push "$RUN_REGION-docker.pkg.dev/$PROJECT_ID/web/$SERVICE_NAME:latest"
    - name: Deploy
      run: |-
        gcloud run deploy "$SERVICE_NAME" \
          --quiet \
          --region "$RUN_REGION" \
          --image "$RUN_REGION-docker.pkg.dev/$PROJECT_ID/web/$SERVICE_NAME:latest" \
          --platform "managed" \
          --allow-unauthenticated \
          --port 80