name: Prod - Build and Deploy

on:
  push:
    branches: [ main ]

env:
  PROJECT_ID: ${{ secrets.PROJECT_ID }}
  SERVICE_NAME: ${{ secrets.SERVICE_NAME }}
  CONTAINER_NAME: ${{ secrets.CONTAINER_NAME }}

jobs:
  setup-build-deploy:
    name: Setup, Build and Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v0'
      with:
        credentials_json: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
    - name: Configure docker
      run: |
        gcloud auth configure-docker europe-docker.pkg.dev
    - name: Build
      run: |
        docker build -t "europe-docker.pkg.dev/$PROJECT_ID/eu.gcr.io/$SERVICE_NAME:$CONTAINER_NAME" .
    - name: Detele previous images
      run: gcloud container images delete "europe-docker.pkg.dev/$PROJECT_ID/eu.gcr.io/$SERVICE_NAME:$CONTAINER_NAME" --force-delete-tags
      continue-on-error: true
    - name: Publish
      run: |
        docker push "europe-docker.pkg.dev/$PROJECT_ID/eu.gcr.io/$SERVICE_NAME:$CONTAINER_NAME"
    - name: Deploy
      run: |-
        gcloud run deploy "$SERVICE_NAME" \
          --quiet \
          --region "${{ secrets.RUN_REGION }}" \
          --image "europe-docker.pkg.dev/$PROJECT_ID/eu.gcr.io/$SERVICE_NAME:$CONTAINER_NAME" \
          --platform "managed" \
          --allow-unauthenticated \
          --port 80